
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author rose ann bahala
 */
public class administrator extends javax.swing.JFrame {

    /**
     * Creates new form administrator
     */
    public administrator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jSplitPane2 = new javax.swing.JSplitPane();
        jPanel10 = new javax.swing.JPanel();
        Cust1 = new javax.swing.JButton();
        Pro1 = new javax.swing.JButton();
        Sal1 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        Inv1 = new javax.swing.JButton();
        dates1 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        Products1 = new javax.swing.JPanel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel13 = new javax.swing.JPanel();
        v2 = new javax.swing.JTextField();
        q1 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        pk1 = new javax.swing.JComboBox<>();
        jLabel36 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        rp2 = new javax.swing.JTextField();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jPanel14 = new javax.swing.JPanel();
        jLabel42 = new javax.swing.JLabel();
        id1 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        v3 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        rp3 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        roi1 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        fp2 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        fp3 = new javax.swing.JTextField();
        DELT = new javax.swing.JButton();
        VIEW = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        scrolInvent = new javax.swing.JScrollPane();
        tab_inventory = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        tab_pro = new javax.swing.JTable();
        Customers1 = new javax.swing.JPanel();
        Employee = new javax.swing.JPanel();
        Sales = new javax.swing.JPanel();
        Inventory = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        inv_table = new javax.swing.JTable();
        text_pro = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel10.setBackground(new java.awt.Color(0, 0, 0));
        jPanel10.setMinimumSize(new java.awt.Dimension(200, 107));
        jPanel10.setPreferredSize(new java.awt.Dimension(200, 107));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Cust1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Cust1.setText("Customers");
        Cust1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Cust1MouseClicked(evt);
            }
        });
        Cust1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Cust1KeyPressed(evt);
            }
        });
        jPanel10.add(Cust1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 140, 37));

        Pro1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Pro1.setText("Products");
        Pro1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Pro1MouseClicked(evt);
            }
        });
        Pro1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Pro1KeyPressed(evt);
            }
        });
        jPanel10.add(Pro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 140, 37));

        Sal1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Sal1.setText("Sales");
        Sal1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Sal1MouseClicked(evt);
            }
        });
        Sal1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Sal1KeyPressed(evt);
            }
        });
        jPanel10.add(Sal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 140, 37));

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton8.setText("Log Out");
        jButton8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton8KeyPressed(evt);
            }
        });
        jPanel10.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 670, 140, 37));

        Inv1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Inv1.setText("Inventory");
        Inv1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Inv1MouseClicked(evt);
            }
        });
        Inv1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Inv1KeyPressed(evt);
            }
        });
        jPanel10.add(Inv1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 140, 37));

        dates1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        dates1.setForeground(new java.awt.Color(0, 204, 204));
        dates1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel10.add(dates1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 120, 30));

        jSplitPane2.setLeftComponent(jPanel10);

        jPanel11.setLayout(new java.awt.CardLayout());

        Products1.setBackground(new java.awt.Color(51, 51, 0));
        Products1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel13.setBackground(new java.awt.Color(153, 153, 0));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        v2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                v2KeyPressed(evt);
            }
        });
        jPanel13.add(v2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 210, -1));
        jPanel13.add(q1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 210, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel20.setText("Per Kilos:");
        jPanel13.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 130, -1));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel24.setText("Variety:");
        jPanel13.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 110, -1));

        pk1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "10", "15", "20", "25", "30", "40", "50" }));
        jPanel13.add(pk1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 210, -1));

        jLabel36.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel36.setText("Quantity:");
        jPanel13.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 130, -1));

        jLabel38.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel38.setText("Regular Price:");
        jPanel13.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 130, -1));
        jPanel13.add(rp2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 210, -1));

        jButton11.setText("Cancel");
        jButton11.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton11KeyPressed(evt);
            }
        });
        jPanel13.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 110, -1));

        jButton12.setText("ADD");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jButton12.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton12KeyPressed(evt);
            }
        });
        jPanel13.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 350, 110, -1));

        jPanel14.setBackground(new java.awt.Color(0, 0, 0));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel42.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(51, 204, 0));
        jLabel42.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel42.setText("0");
        jPanel14.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, 160, -1));

        id1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        id1.setForeground(new java.awt.Color(51, 204, 0));
        id1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel14.add(id1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 270, 30));

        jLabel44.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(255, 255, 255));
        jLabel44.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel44.setText("Total Sales");
        jPanel14.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 160, -1));

        jLabel45.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(51, 204, 0));
        jLabel45.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel45.setText("0");
        jPanel14.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 160, -1));

        jLabel46.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(255, 255, 255));
        jLabel46.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel46.setText("Product Quantity");
        jPanel14.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 170, -1));

        jLabel47.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(51, 204, 0));
        jLabel47.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel47.setText("0");
        jPanel14.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 160, -1));

        jLabel48.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(255, 255, 255));
        jLabel48.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel48.setText(" Sales Purchased");
        jPanel14.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, 160, -1));

        jLabel49.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(51, 204, 0));
        jLabel49.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel49.setText("0");
        jPanel14.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 350, 160, -1));

        jLabel50.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(255, 255, 255));
        jLabel50.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel50.setText("Quantity Purchased");
        jPanel14.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, 180, -1));

        jLabel51.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(255, 255, 255));
        jLabel51.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel51.setText("Product ID:");
        jPanel14.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 20, 140, 30));

        v3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        v3.setForeground(new java.awt.Color(51, 204, 0));
        v3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel14.add(v3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 270, 30));

        jLabel52.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(255, 255, 255));
        jLabel52.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel52.setText("Variety:");
        jPanel14.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 140, 30));

        rp3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rp3.setForeground(new java.awt.Color(51, 204, 0));
        rp3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel14.add(rp3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 270, 30));

        jLabel53.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel53.setForeground(new java.awt.Color(255, 255, 255));
        jLabel53.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel53.setText("Regular Price:");
        jPanel14.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 140, 30));

        roi1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        roi1.setForeground(new java.awt.Color(51, 204, 0));
        roi1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel14.add(roi1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 270, 40));

        jLabel54.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel54.setForeground(new java.awt.Color(255, 255, 255));
        jLabel54.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel54.setText("ROI:");
        jPanel14.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 180, 140, 40));
        jPanel14.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 460, 20));

        fp2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        fp2.setForeground(new java.awt.Color(51, 204, 0));
        fp2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel14.add(fp2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 270, 30));

        jLabel55.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel55.setForeground(new java.awt.Color(255, 255, 255));
        jLabel55.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel55.setText("Fixed Price:");
        jPanel14.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 140, 30));

        jPanel13.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, 460, 390));

        jLabel56.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel56.setForeground(new java.awt.Color(255, 255, 255));
        jLabel56.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel56.setText("Fixed Price:");
        jPanel13.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 130, -1));

        fp3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fp3KeyPressed(evt);
            }
        });
        jPanel13.add(fp3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 210, -1));

        jTabbedPane3.addTab("Products", jPanel13);

        Products1.add(jTabbedPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 440));

        DELT.setText("Delete");
        DELT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DELTActionPerformed(evt);
            }
        });
        DELT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                DELTKeyPressed(evt);
            }
        });
        Products1.add(DELT, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 720, 130, -1));

        VIEW.setText("View");
        VIEW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VIEWActionPerformed(evt);
            }
        });
        VIEW.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                VIEWKeyPressed(evt);
            }
        });
        Products1.add(VIEW, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 720, 130, -1));

        jPanel5.setLayout(new java.awt.CardLayout());

        tab_inventory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Inventory ID", "Pro_ID", "Regular Price", "Fixed Price", "Total ROI", "Quantity Purchased", "Total Quantity"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrolInvent.setViewportView(tab_inventory);

        jPanel5.add(scrolInvent, "card2");

        tab_pro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product Id", "Variety", "Price", "Quantity"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tab_pro);

        jPanel5.add(jScrollPane1, "card3");

        Products1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 880, 250));

        jPanel11.add(Products1, "card2");

        javax.swing.GroupLayout Customers1Layout = new javax.swing.GroupLayout(Customers1);
        Customers1.setLayout(Customers1Layout);
        Customers1Layout.setHorizontalGroup(
            Customers1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 901, Short.MAX_VALUE)
        );
        Customers1Layout.setVerticalGroup(
            Customers1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 776, Short.MAX_VALUE)
        );

        jPanel11.add(Customers1, "card3");

        javax.swing.GroupLayout EmployeeLayout = new javax.swing.GroupLayout(Employee);
        Employee.setLayout(EmployeeLayout);
        EmployeeLayout.setHorizontalGroup(
            EmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 901, Short.MAX_VALUE)
        );
        EmployeeLayout.setVerticalGroup(
            EmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 776, Short.MAX_VALUE)
        );

        jPanel11.add(Employee, "card4");

        javax.swing.GroupLayout SalesLayout = new javax.swing.GroupLayout(Sales);
        Sales.setLayout(SalesLayout);
        SalesLayout.setHorizontalGroup(
            SalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 901, Short.MAX_VALUE)
        );
        SalesLayout.setVerticalGroup(
            SalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 776, Short.MAX_VALUE)
        );

        jPanel11.add(Sales, "card5");

        inv_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Inventory ID", "Product", "Price", "Quantity", "purchased"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(inv_table);

        text_pro.setText("jTextField1");

        javax.swing.GroupLayout InventoryLayout = new javax.swing.GroupLayout(Inventory);
        Inventory.setLayout(InventoryLayout);
        InventoryLayout.setHorizontalGroup(
            InventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InventoryLayout.createSequentialGroup()
                .addGroup(InventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InventoryLayout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(InventoryLayout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(text_pro, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(172, Short.MAX_VALUE))
        );
        InventoryLayout.setVerticalGroup(
            InventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InventoryLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(text_pro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 354, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );

        jPanel11.add(Inventory, "card6");

        jSplitPane2.setRightComponent(jPanel11);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jSplitPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jSplitPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 778, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1110, 760));

        jTabbedPane1.addTab("Transactions", jPanel2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1483, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 760, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Employees", jPanel3);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Cust1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Cust1MouseClicked
        customer();
        cust_color();
    }//GEN-LAST:event_Cust1MouseClicked

    private void Cust1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Cust1KeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            customer();
            cust_color();
        }
    }//GEN-LAST:event_Cust1KeyPressed

    private void Pro1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pro1MouseClicked
        product();
        pro_color();
    }//GEN-LAST:event_Pro1MouseClicked

    private void Pro1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Pro1KeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            product();
            pro_color();
        }
    }//GEN-LAST:event_Pro1KeyPressed

    private void Sal1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Sal1MouseClicked
        sale();
        sal_color();
    }//GEN-LAST:event_Sal1MouseClicked

    private void Sal1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Sal1KeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            sale();
            sal_color();
        }
    }//GEN-LAST:event_Sal1KeyPressed

    private void jButton8KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton8KeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            JOptionPane.showConfirmDialog(rootPane, "Are You Sure,?","Log out", JOptionPane.YES_NO_OPTION);
            this.dispose();
            new first().setVisible(true);
        }
    }//GEN-LAST:event_jButton8KeyPressed

    private void Inv1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Inv1MouseClicked
        invent();
        inv_color();
    }//GEN-LAST:event_Inv1MouseClicked

    private void Inv1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Inv1KeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            invent();
            inv_color();
        }
    }//GEN-LAST:event_Inv1KeyPressed

    private void v2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_v2KeyPressed
       products();
    }//GEN-LAST:event_v2KeyPressed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        purchased();
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton12KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton12KeyPressed
      if(evt.getKeyCode()==KeyEvent.VK_ENTER){
           purchased();
      }
          
    }//GEN-LAST:event_jButton12KeyPressed

    private void VIEWKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_VIEWKeyPressed
      VIEW.setBackground(Color.yellow);
        VIEW.setForeground(Color.BLACK);
        DELT.setBackground(Color.red);
        DELT.setForeground(Color.WHITE);
      products();
        
    }//GEN-LAST:event_VIEWKeyPressed

    private void VIEWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VIEWActionPerformed
        products();
    }//GEN-LAST:event_VIEWActionPerformed

    private void fp3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fp3KeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
           purchased();
      }
        
    }//GEN-LAST:event_fp3KeyPressed

    private void jButton11KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton11KeyPressed
      if (evt.getKeyCode()==KeyEvent.VK_ENTER){
                 q1.setText("");
                v2.setText("");
                rp2.setText("");
                fp3.setText("");
                pk1.setSelectedItem(0);
                products();
      }
    }//GEN-LAST:event_jButton11KeyPressed

    private void DELTKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DELTKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER){
             int del1= tab_inventory.getSelectedRow();
        if (del1 !=-1){

            if (JOptionPane.showConfirmDialog(rootPane, "Are you sure you want to delete?", "Delete Product", JOptionPane.YES_NO_OPTION)==0){

                String inv=tab_inventory.getValueAt(del1, 0).toString();
                String pro=tab_pro.getValueAt(del1, 0).toString();
                
                try{
                    Class.forName("com.mysql.jdbc.Driver");
                    String conURL="jdbc:mysql://localhost/system?"
                    + "user=root&password=";
                    Connection cont=DriverManager.getConnection(conURL);
                    
                  Statement del3 = cont.createStatement();
                  String dell3 = "DELETE FROM `inventory_sell` WHERE `inv_id`= "+inv+";";
                 ResultSet rs1 = del3.executeQuery(dell3);
                 rs1.next();
                    
                
                    JOptionPane.showMessageDialog(rootPane, "Successfully Deleted");
                    products();

                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(administrator.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(administrator.class.getName()).log(Level.SEVERE, null, ex);
                }

            }
        }
        }
    }//GEN-LAST:event_DELTKeyPressed

    private void DELTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DELTActionPerformed
        
             int del1= tab_inventory.getSelectedRow();
        if (del1 !=-1){

            if (JOptionPane.showConfirmDialog(rootPane, "Are you sure you want to delete?", "Delete Product", JOptionPane.YES_NO_OPTION)==0){

                String del2=tab_inventory.getValueAt(del1, 0).toString();
                
                try{
                    Class.forName("com.mysql.jdbc.Driver");
                    String conURL="jdbc:mysql://localhost/system?"
                    + "user=root&password=";
                    Connection cont=DriverManager.getConnection(conURL);
                    
                  Statement del3 = cont.createStatement();
                  String dell3 = "DELETE FROM `inventory_sell` WHERE `inv_id`= "+del2+";";
                 ResultSet rs1 = del3.executeQuery(dell3);
                 rs1.next();
               
                    
                    JOptionPane.showMessageDialog(rootPane, "Successfully Deleted");
                    products();

                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(administrator.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(administrator.class.getName()).log(Level.SEVERE, null, ex);
                }

            }
        
        }
        
    }//GEN-LAST:event_DELTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(administrator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(administrator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(administrator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(administrator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new administrator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cust1;
    private javax.swing.JPanel Customers1;
    private javax.swing.JButton DELT;
    private javax.swing.JPanel Employee;
    private javax.swing.JButton Inv1;
    private javax.swing.JPanel Inventory;
    private javax.swing.JButton Pro1;
    private javax.swing.JPanel Products1;
    private javax.swing.JButton Sal1;
    private javax.swing.JPanel Sales;
    private javax.swing.JButton VIEW;
    private javax.swing.JLabel dates1;
    private javax.swing.JLabel fp2;
    private javax.swing.JTextField fp3;
    private javax.swing.JLabel id1;
    private javax.swing.JTable inv_table;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JComboBox<String> pk1;
    private javax.swing.JTextField q1;
    private javax.swing.JLabel roi1;
    private javax.swing.JTextField rp2;
    private javax.swing.JLabel rp3;
    private javax.swing.JScrollPane scrolInvent;
    private javax.swing.JTable tab_inventory;
    private javax.swing.JTable tab_pro;
    private javax.swing.JTextField text_pro;
    private javax.swing.JTextField v2;
    private javax.swing.JLabel v3;
    // End of variables declaration//GEN-END:variables

 private void product() {
        Products1.setVisible(true);
        Customers1.setVisible(false);
       Employee.setVisible(false);
       Sales.setVisible(false);
        Inventory.setVisible(false);  
}

    private void customer() {
        Products1.setVisible(false);
        Customers1.setVisible(true);
       Employee.setVisible(false);
       Sales.setVisible(false);
        Inventory.setVisible(false); 

    }

    private void employ() {
        Products1.setVisible(false);
        Customers1.setVisible(false);
       Employee.setVisible(true);
       Sales.setVisible(false);
        Inventory.setVisible(false); 

    }

    private void sale() {
        Products1.setVisible(false);
        Customers1.setVisible(false);
       Employee.setVisible(false);
       Sales.setVisible(true);
        Inventory.setVisible(false); 
    }

    private void invent() {
        Products1.setVisible(false);
        Customers1.setVisible(false);
       Employee.setVisible(false);
       Sales.setVisible(false);
        Inventory.setVisible(true); 
    }

    private void pro_color() {
        Pro1.setBackground(Color.yellow);
        Pro1.setForeground(Color.BLACK);
        Cust1.setBackground(Color.WHITE);
        Cust1.setForeground(Color.BLACK);
        Sal1.setBackground(Color.WHITE);
        Sal1.setForeground(Color.BLACK);
        Inv1.setBackground(Color.WHITE);
        Inv1.setForeground(Color.BLACK);
}

    private void cust_color() {
       Pro1.setBackground(Color.WHITE);
        Pro1.setForeground(Color.BLACK);
        Cust1.setBackground(Color.yellow);
        Cust1.setForeground(Color.BLACK);
        Sal1.setBackground(Color.WHITE);
        Sal1.setForeground(Color.BLACK);
        Inv1.setBackground(Color.WHITE);
        Inv1.setForeground(Color.BLACK);
    }

    private void emp_color() {
       Pro1.setBackground(Color.WHITE);
        Pro1.setForeground(Color.BLACK);
        Cust1.setBackground(Color.WHITE);
        Cust1.setForeground(Color.BLACK);
        Sal1.setBackground(Color.WHITE);
        Sal1.setForeground(Color.BLACK);
        Inv1.setBackground(Color.WHITE);
        Inv1.setForeground(Color.BLACK);
    }

    private void sal_color() {
        Pro1.setBackground(Color.WHITE);
        Pro1.setForeground(Color.BLACK);
        Cust1.setBackground(Color.WHITE);
        Cust1.setForeground(Color.BLACK);
       Sal1.setBackground(Color.yellow);
        Sal1.setForeground(Color.BLACK);
        Inv1.setBackground(Color.WHITE);
        Inv1.setForeground(Color.BLACK);
    }

    private void inv_color() {
        Pro1.setBackground(Color.WHITE);
        Pro1.setForeground(Color.BLACK);
        Cust1.setBackground(Color.WHITE);
        Cust1.setForeground(Color.BLACK);
       Sal1.setBackground(Color.WHITE);
        Sal1.setForeground(Color.BLACK);
        Inv1.setBackground(Color.YELLOW);
        Inv1.setForeground(Color.BLACK);
    }

   void products() {
       try { 
           String inName1=fp3.getText();
          
            try {
            Class.forName("com.mysql.jdbc.Driver");
            String conURL="jdbc:mysql://localhost/system?"
            + "user=root&password=";
            Connection con1;
            con1=DriverManager.getConnection(conURL);
            Statement nezir1=con1.createStatement();
            String sql1 = "select * from inventory_sell WHERE true";
          
            if(inName1!=null){
                sql1 = sql1 + " AND (pro_fix_price like '%"+inName1+"%')";
              }
            
             
             
            System.out.println(sql1);
            ResultSet rs1 = nezir1.executeQuery(sql1);
            DefaultTableModel model= new ProductModel().ProModel;
            int kami=0;
            
            while(rs1.next()){
                model.addRow(new Object[]{});
                model.setValueAt(rs1.getString("inv_id"), kami, 0);
                model.setValueAt(rs1.getString("pro_id"), kami, 1);
                model.setValueAt(rs1.getString("pro_reg_price"), kami, 2);
                model.setValueAt(rs1.getString("pro_fix_price"), kami, 3);
                model.setValueAt(rs1.getString("pro_roi"), kami, 4);
                model.setValueAt(rs1.getString("pro_quant_purch"), kami, 5);
                model.setValueAt(rs1.getString("total_quant"), kami, 6);
               
                 kami++;
            }
           tab_inventory.setModel(model);
            } catch (SQLException ex) {
                Logger.getLogger(administrator.class.getName()).log(Level.SEVERE, null, ex);
            }
             } catch (ClassNotFoundException ex) {
                Logger.getLogger(administrator.class.getName()).log(Level.SEVERE, null, ex);
            }
   
    }

    private void purchased() {
       

            try {
                String a = v2.getText();
                String b = rp2.getText();
                int d2 =Integer.parseInt(rp2.getText());
                String c = fp3.getText();
                int d3 =Integer.parseInt(fp3.getText());
                String e = q1.getText();
                String f = q1.getText();
                String g = 0+"";
                String dif;
                dif = d3-d2+"";

                Class.forName("com.mysql.jdbc.Driver");
                String conURL="jdbc:mysql://localhost/system?"
                + "user=root&password=";
                Connection lag= DriverManager.getConnection(conURL);

               
                
                PreparedStatement pro1=(PreparedStatement) lag.prepareStatement("insert into `products`(`pro_variety`,`pro_price`,`pro_quantity`)"
                         + "values ('"+a+"','"+c+"','"+f+"');");
                 pro1.executeUpdate();
                
                 Statement stmt5 = lag.createStatement();
                 String declare5 = "SELECT * FROM `products` WHERE pro_variety='"+a+"'";
                 ResultSet rs5 = stmt5.executeQuery(declare5);
                 rs5.next();

                 int proID = rs5.getInt("pro_id");
                  
                PreparedStatement pro=(PreparedStatement) lag.prepareStatement("insert into `inventory_sell`(`pro_id`,`pro_reg_price`"
                    + ",`pro_fix_price`,`pro_roi`,`pro_quant_purch`,`total_quant`)values('"+proID+"','"+b+"','"+c+"','"+dif+"','"+g+"','"+e+"');");
                 pro.executeUpdate();
                 
                JOptionPane.showMessageDialog(rootPane,"Successfully added the Product");
                
                products();
                pk1.setSelectedItem(0);
                id1.setText(proID+"");
                v3.setText(a);
                rp3.setText(b);
                fp2.setText(c);
                roi1.setText(dif);
                q1.setText("");
                v2.setText("");
                rp2.setText("");
                fp3.setText("");
              

            } catch (ClassNotFoundException ex) {
                Logger.getLogger(administrator.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(administrator.class.getName()).log(Level.SEVERE, null, ex);
            }
       }
    
}